# Generated by Django 2.1.2 on 2018-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('F', 'First Player to Move'), ('S', 'Second Player to Move'), ('W', 'First Player Win'), ('L', 'Second Player Win'), ('D', 'Draw')], default='F', max_length=1),
        ),
    ]
